---
  language: go
  sudo: false
  notifications:
    email: true
  go:
    - 1.x
    - tip
  matrix:
    allow_failures:
      - go: tip
    fast_finish: true
  install:
    - go get github.com/golang/lint/golint
    - go get honnef.co/go/tools/cmd/staticcheck
  script:
    - make all
    - make cover
    - make release
  after_success:
    - bash <(curl -s https://codecov.io/bash)
  deploy:
    provider: releases
    api_key:
      secure: "bYFfZ9KCvIGLFDEp8xlaE28SLCFIzYWqX63amsGY2iyT2ybMINQTVTAebzRvkFKI8tXHq2rlHRVJ/SNNklelv5Fjt/yhFIV6QM2tKeJ+sh3TWRGC03v/BdyjlVo3yPddYRQiUWpf8uKhZp7IVLfaEPz5xR42mcYAKk1DP+rm7pn/Jwm4ORxcgEtgdmIyzTIApAMlMwAQbJekZVSpDoOOrOdVySqGOvzbCbg253svOA+ulFv+AYxLU7HWlE86wLyZYtsK+xSmwmrg2Gzn7Is92MuZgWBBVF7IvKIkDto06TNHzJiL2eAjCGM+Y2oyUT1xycgtbx1LB4MC4ZrSXLnJ2x6Tw1CxrPgMZJ/ij0DY5yxeU1jo1LtwHXyR1G5gd8WcrZ8hYGLSw1vllFjNUgS83DE5QZIajYmVJIUn7JBjSvFoTffYDDOPPQUJ+1uy5VtQte0rEPR7au2GXle9Vp2tHsPGlQw7I/VXapbu4QMIWHcgnOElFYdWzYLV0jntpDTc9xShux9/RhCBObehaI36JJDqVnur6444ahEVOFWfhViEqTXp1aRuGuHoU0nycOvzlD1KKdyHpinhpmLrayhZdack1jr/Mnj7ot26VBaOHQAZ9yXNGWReBNOQoU9yHuOu8vZW3K3MMa8P4Es4WqZC5glQ3Lf+QeemLexkqLVoc30="
    file:
      - cross/dockfmt-linux-amd64.md5
      - cross/dockfmt-windows-386.sha256
      - cross/dockfmt-linux-arm
      - cross/dockfmt-darwin-amd64.md5
      - cross/dockfmt-darwin-amd64
      - cross/dockfmt-solaris-amd64.md5
      - cross/dockfmt-linux-arm64.sha256
      - cross/dockfmt-linux-arm.sha256
      - cross/dockfmt-linux-386.sha256
      - cross/dockfmt-darwin-386.md5
      - cross/dockfmt-windows-386.md5
      - cross/dockfmt-freebsd-amd64.md5
      - cross/dockfmt-linux-arm64.md5
      - cross/dockfmt-linux-arm64
      - cross/dockfmt-freebsd-amd64.sha256
      - cross/dockfmt-freebsd-386.md5
      - cross/dockfmt-linux-amd64.sha256
      - cross/dockfmt-linux-386.md5
      - cross/dockfmt-freebsd-386
      - cross/dockfmt-solaris-amd64.sha256
      - cross/dockfmt-windows-amd64
      - cross/dockfmt-windows-amd64.md5
      - cross/dockfmt-windows-amd64.sha256
      - cross/dockfmt-linux-arm.md5
      - cross/dockfmt-darwin-386.sha256
      - cross/dockfmt-darwin-amd64.sha256
      - cross/dockfmt-windows-386
      - cross/dockfmt-solaris-amd64
      - cross/dockfmt-darwin-386
      - cross/dockfmt-linux-386
      - cross/dockfmt-freebsd-amd64
      - cross/dockfmt-freebsd-386.sha256
      - cross/dockfmt-linux-amd64
    skip_cleanup: true
    on:
      tags: true
